HW16
Mr-Cheen1/home_work pull request #15
Opened 2024-03-28 15:04 UTC by Mr-Cheen1

## Домашнее задание №16 «Контейнеризация приложения»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)

### Критерии оценки
- [ ] Реализован Dockerfile - 2 балла
- [ ] Реализован docker-compose - 2 балла
- [ ] Приложение собирается и взаимодейтсвует с БД - 2 балла

#### Зачёт от 4 баллов

2024-03-29 19:10 UTC, vladislavmass requested changes

2024-03-29 19:10 UTC, vladislavmass commented on hw16_docker/server/Dockerfile
> +RUN CGO_ENABLED=0 go build -o server ./server/main.go
Тут однозначный конфликт путей. Данная строка пытается в каталоге app создать файл  с именем server, при этом в этом каталоге уже есть каталог с именем server. Поэтому бинарный файл с именем server не создается, а когда идет копирование на образ где будет запуск, то копируется на исполняемый файл а папка server. И естественно  запустить папку невозможно

2024-04-01 02:20 UTC, Mr-Cheen1 commented
Можно слить в главную ветку ? Задание в чате OTUS приняли.

2024-04-01 03:03 UTC, vladislavmass approved these changes

2024-04-01 03:04 UTC, vladislavmass commented
> Можно слить в главную ветку ? Задание в чате OTUS приняли.

Да, можете

2024-04-01 04:22 UTC, merged